import { test, expect } from '@playwright/test';

test('testAboutPage', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.getByRole('heading', { name: 'Welcome to NumberSense' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: '' }).nth(1).press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/');
  await page.getByRole('heading', { name: 'About the NumberSense Mathematics Programme' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/programme-overview/');
  await page.getByRole('heading', { name: 'NumberSense Mathematics Programme Overview' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/numbersense-in-the-classroom/');
  await page.getByRole('heading', { name: 'NumberSense in the Classroom' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/numbersense-app-about/');
  await page.getByRole('heading', { name: 'The NumberSense Mobile App' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/mathssense/');
  await page.getByRole('heading', { name: 'MathsSense' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/theoretical-underpinnings/');
  await page.getByRole('heading', { name: 'Theoretical Underpinnings of the Programme' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/concept-development/');
  await page.getByRole('heading', { name: 'Concept Development' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/faqs/');
  await page.getByRole('heading', { name: 'FAQs, Testimonials & Affiliates' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/about/become-a-numbersense-reseller/');
  await page.getByRole('heading', { name: 'Become a NumberSense reseller' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/');
});


test('testResourcesPage', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/');
  await page.getByRole('heading', { name: 'Resources' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/teacher-guides/');
  await page.getByRole('heading', { name: 'Teacher Guides' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/teach-plan-curriculum/');
  await page.getByRole('heading', { name: 'Teaching, Planning & Curriculum' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/assessment/');
  await page.getByRole('heading', { name: 'Assessment' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/manipulating-numbers/');
  await page.getByRole('heading', { name: 'Manipulating Numbers' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/teaching-resources/');
  await page.getByRole('heading', { name: 'Teaching Resources' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/readings-handouts/');
  await page.getByRole('heading', { name: 'Readings and Handouts' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/resources/numbersense-app-resources/');
  await page.getByRole('heading', { name: 'The NumberSense Mobile App' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
});


test('testVideoPage', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/');
  await page.getByRole('heading', { name: 'Videos' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/numbersense-routines/');
  await page.getByRole('heading', { name: 'The NumberSense Routines' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/manipulating-numbers/');
  await page.getByRole('heading', { name: 'Manipulating Numbers Videos' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).click();
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Manipulating Number Video Description and Examples ' }).press('ArrowDown');
  await page.getByRole('link', { name: '' }).first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/webinar-recordings/');
  await page.getByRole('heading', { name: 'Webinar Recordings' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/mathssense/');
  await page.getByRole('heading', { name: 'MathsSense' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: '' }).first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.getByRole('link', { name: '' }).first().press('ArrowUp');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/');
  await page.getByRole('heading', { name: 'Videos' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/videos/a-world-record/');
  await page.getByRole('heading', { name: 'A GeoGenius World Record' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('.video-btn').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.locator('.video-btn').first().press('ArrowUp');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
});


test('testShopPage', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/shop/');
  await page.getByRole('heading', { name: 'Shop' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/workbooks/');
  await page.getByRole('heading', { name: 'NumberSense Workbooks' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/companion-materials/');
  await page.getByRole('heading', { name: 'Companion Materials' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/geogenius-kits/');
  await page.getByRole('heading', { name: 'GeoGenius Kits' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/app-licenses/');
  await page.getByRole('heading', { name: 'NumberSense App licenses' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/resources/');
  await page.getByRole('heading', { name: 'NumberSense Resources' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/events/');
  await page.getByRole('heading', { name: 'Events' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/order-form/');
  await page.getByRole('heading', { name: 'Order Form' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/product-category/mathssense/');
  await page.getByRole('heading', { name: 'MathsSense Mathematics Programme (Grade 8 & 9)' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
});


test('testAppPage', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/mobile-app/');
  await page.getByRole('heading', { name: 'The NumberSense Mobile App' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/mobile-app/about-the-app/');
  await page.getByRole('heading', { name: 'About the NumberSense App' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/mobile-app/using-the-app/');
  await page.getByRole('heading', { name: 'Using the NumberSense App' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: 'Using the App Step 1: Download the NumberSense App User Guide ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 1: Download the NumberSense App User Guide ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 2: Download the App ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 2: Download the App ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 3: Purchase the NumberSense Workbook App license ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 3: Purchase the NumberSense Workbook App license ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 4: Use the username and password supplied to log in and start your NumberSense journey! ' }).click();
  await page.getByRole('link', { name: 'Using the App Step 4: Use the username and password supplied to log in and start your NumberSense journey! ' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/mobile-app/the-app-console/');
  await page.getByRole('heading', { name: 'The App Console' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'App Console', exact: true }).click();
  const page1 = await page1Promise;
});

test('testEventsAndWebinars', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/events/');
  await page.getByRole('heading', { name: 'Events' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/events/workshops/');
  await page.getByRole('heading', { name: 'Workshops' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/events/workshops/ws-cape-town/');
  await page.getByRole('heading', { name: 'Cape Town' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/events/conferences/');
  await page.getByRole('heading', { name: 'Conferences' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/webinars/');
  await page.getByRole('heading', { name: 'Webinars' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: 'Webinar recordings', exact: true }).click();
  await page1.getByRole('heading', { name: 'Webinar Recordings' }).click();
});


test('test', async ({ page }) => {
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/');
  await page.getByRole('heading', { name: 'Welcome to NumberSense' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/contact/');
  await page.getByRole('heading', { name: 'Contact Us' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('heading', { name: 'Map' }).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).click();
  await page.getByRole('link', { name: 'Contact Us ' }).click();
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Contact Us ' }).press('ArrowDown');
  await page.getByLabel('Name *').click();
  await page.getByLabel('Name *').press('CapsLock');
  await page.getByLabel('Name *').fill('T');
  await page.getByLabel('Name *').press('CapsLock');
  await page.getByLabel('Name *').fill('Test');
  await page.getByLabel('Email *').click();
  await page.getByLabel('Email *').fill('testingtesttest@mailinator.com');
  await page.getByLabel('Your Message *').click();
  await page.getByLabel('Your Message *').press('CapsLock');
  await page.getByLabel('Your Message *').fill('T');
  await page.getByLabel('Your Message *').press('CapsLock');
  await page.getByLabel('Your Message *').fill('This is a test');
  await page.frameLocator('iframe[name="a-all9pd3tmkvg"]').getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.goto('https://numbersense-co-za-san-uat.azurewebsites.net/contact/');
  await page.getByText('Thanks for contacting us! We will be in touch with you shortly.').click();
});

// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('https://www.google.com/search?q=numbersense&oq=numbersense&aqs=chrome..69i57.5947j0j2&sourceid=chrome&ie=UTF-8');
//   await page.getByRole('link', { name: 'NumberSense: Home NumberSense.co.za https://www.numbersense.co.za' }).click();
//   await page.getByRole('link', { name: 'Contact' }).click();
//   await page.getByRole('heading', { name: 'Contact Us' }).click();
//   await page.locator('#menu-item-111').getByRole('link', { name: 'Shop' }).click();
//   await page.getByText('NumberSense Workbook 9').click();
//   await page.locator('div:nth-child(16) > .image-wrap > .attachment-img_prod_237x132').click();
//   await page.locator('div:nth-child(16) > .card-btn-holder > .card-btn').click();
// });